
// This file has been generated by the GUI designer. Do not modify.
namespace br.com.lassal.Agenda.GtkApp.Widgets
{
	public partial class EntryErrorValidation
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Entry TextEntry;
		
		private global::Gtk.Image ErrorImage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget br.com.lassal.Agenda.GtkApp.Widgets.EntryErrorValidation
			global::Stetic.BinContainer.Attach (this);
			this.Name = "br.com.lassal.Agenda.GtkApp.Widgets.EntryErrorValidation";
			// Container child br.com.lassal.Agenda.GtkApp.Widgets.EntryErrorValidation.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.TextEntry = new global::Gtk.Entry ();
			this.TextEntry.CanFocus = true;
			this.TextEntry.Name = "TextEntry";
			this.TextEntry.IsEditable = true;
			this.TextEntry.InvisibleChar = '●';
			this.hbox1.Add (this.TextEntry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.TextEntry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ErrorImage = new global::Gtk.Image ();
			this.ErrorImage.WidthRequest = 22;
			this.ErrorImage.HeightRequest = 22;
			this.ErrorImage.Name = "ErrorImage";
			this.ErrorImage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-stop", global::Gtk.IconSize.Menu);
			this.hbox1.Add (this.ErrorImage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ErrorImage]));
			w2.Position = 1;
			w2.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.ErrorImage.Hide ();
			this.Hide ();
		}
	}
}
