//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.lassal.Agenda.PM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgendaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgendaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("br.com.lassal.Agenda.PM.Resources.AgendaResources", typeof(AgendaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        internal static string AgendaFormTitle {
            get {
                return ResourceManager.GetString("AgendaFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma cidade para este contato .
        /// </summary>
        internal static string ContactEdit_Edit_CityErrorMSG {
            get {
                return ResourceManager.GetString("ContactEdit_Edit_CityErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um país para este contato.
        /// </summary>
        internal static string ContactEdit_Edit_CountryErrorMSG {
            get {
                return ResourceManager.GetString("ContactEdit_Edit_CountryErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa informar algum nome para identificação. Por favor informe um o primeiro nome, o sobronome ou o apelido do contato.
        /// </summary>
        internal static string ContactEdit_Edit_NameErrorMSG {
            get {
                return ResourceManager.GetString("ContactEdit_Edit_NameErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar contato.
        /// </summary>
        internal static string ContactList_Search_BoxName {
            get {
                return ResourceManager.GetString("ContactList_Search_BoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string ContactList_Search_City {
            get {
                return ResourceManager.GetString("ContactList_Search_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string ContactList_Search_Country {
            get {
                return ResourceManager.GetString("ContactList_Search_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string ContactList_Search_Name {
            get {
                return ResourceManager.GetString("ContactList_Search_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string ContactList_Search_SearchCMD {
            get {
                return ResourceManager.GetString("ContactList_Search_SearchCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca inválida. Informe ao menos um nome, ou cidade ou país do contato procurado.
        /// </summary>
        internal static string ContactList_Search_SearchErrorMSG {
            get {
                return ResourceManager.GetString("ContactList_Search_SearchErrorMSG", resourceCulture);
            }
        }
    }
}
