
// This file has been generated by the GUI designer. Do not modify.
namespace br.com.lassal.Agenda.GtkApp
{
	public partial class TWindow
	{
		private global::Gtk.VPaned vpaned1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget br.com.lassal.Agenda.GtkApp.TWindow
			this.Name = "br.com.lassal.Agenda.GtkApp.TWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child br.com.lassal.Agenda.GtkApp.TWindow.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add (this.textview1);
			this.vpaned1.Add (this.GtkScrolledWindow);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
